[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "frontend/netlify/functions"

# AI Facial recognition neural network models
[[headers]]
  for = "/models/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/*"
  to = "https://ait-ncc.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
